# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of redmine systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ redmine_identifier }}.service"
  register: redmine_service_stat

- when: redmine_service_stat.stat.exists | bool
  block:
    - name: Ensure redmine systemd unites are stopped
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        daemon_reload: true
      with_items:
        - "{{ redmine_identifier }}.service"
        - "{{ redmine_identifier }}-send-reminders.service"
        - "{{ redmine_identifier }}-send-reminders.timer"

    - name: Ensure redmine recurring tasks systemd unites are stopped
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
        daemon_reload: true
      when: redmine_recurring_tasks_enabled | bool
      with_items:
        - "{{ redmine_identifier }}-recurring-tasks.service"
        - "{{ redmine_identifier }}-recurring-tasks.timer"

    - name: Ensure redmine data removed
      ansible.builtin.file:
        path: "{{ redmine_base_path }}"
        state: absent

    - name: Ensure redmine systemd units do not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ item }}"
        state: absent
      with_items:
        - "{{ redmine_identifier }}.service"
        - "{{ redmine_identifier }}-send-reminders.service"
        - "{{ redmine_identifier }}-send-reminders.timer"
        - "{{ redmine_identifier }}-recurring-tasks.service"
        - "{{ redmine_identifier }}-recurring-tasks.timer"
